"""add inventory balances and stock movements

Revision ID: db993ddf412b
Revises: e360bc96b37e
Create Date: 2026-08-26 13:57:49.116460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db993ddf412b'
down_revision: Union[str, Sequence[str], None] = 'e360bc96b37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_balances_on_hand_non_negative'),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name='ck_inventory_balances_reserved_not_above_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_inventory_balances_reserved_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_inventory_balances_product_warehouse')
    )
    op.create_index(op.f('ix_inventory_balances_product_id'), 'inventory_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_warehouse_id'), 'inventory_balances', ['warehouse_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('on_hand_delta', sa.Integer(), nullable=False),
    sa.Column('reserved_delta', sa.Integer(), nullable=False),
    sa.Column('on_hand_balance_after', sa.Integer(), nullable=False),
    sa.Column('reserved_balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            movement_type IN (\n                'RECEIPT',\n                'ISSUE',\n                'ADJUSTMENT',\n                'RESERVATION',\n                'RELEASE'\n            )\n            ", name='ck_stock_movements_valid_type'),
    sa.CheckConstraint('on_hand_balance_after >= 0', name='ck_stock_movements_on_hand_after_non_negative'),
    sa.CheckConstraint('on_hand_delta <> 0 OR reserved_delta <> 0', name='ck_stock_movements_non_zero_delta'),
    sa.CheckConstraint('reserved_balance_after >= 0', name='ck_stock_movements_reserved_after_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_product_warehouse_created', 'stock_movements', ['product_id', 'warehouse_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_product_warehouse_created', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_inventory_balances_warehouse_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_product_id'), table_name='inventory_balances')
    op.drop_table('inventory_balances')
    # ### end Alembic commands ###
