"""create incidents

Revision ID: 429cf66dee96
Revises: 6f0b4cf1a0f3
Create Date: 2026-09-16 09:27:23.129221

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "429cf66dee96"
down_revision: str | Sequence[str] | None = "6f0b4cf1a0f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_anomaly_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=100), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=100), nullable=True),
        sa.Column("resolution_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"], ["monitored_services.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trigger_anomaly_id"], ["anomaly_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "trigger_anomaly_id", name="uq_incidents_trigger_anomaly_id"
        ),
    )
    op.create_index(
        "ix_incident_service_status",
        "incidents",
        ["service_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_incident_severity_created_at",
        "incidents",
        ["severity", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_incident_status_created_at",
        "incidents",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incident_status_created_at", table_name="incidents")
    op.drop_index("ix_incident_severity_created_at", table_name="incidents")
    op.drop_index("ix_incident_service_status", table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
