"""create anomaly records

Revision ID: 6f0b4cf1a0f3
Revises: fbdf46a4e529
Create Date: 2026-09-15 17:03:19.971517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f0b4cf1a0f3"
down_revision: str | Sequence[str] | None = "fbdf46a4e529"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomaly_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telemetry_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("observed_value", sa.JSON(), nullable=False),
        sa.Column("threshold", sa.JSON(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telemetry_id"], ["telemetry_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomaly_records_telemetry_id"),
        "anomaly_records",
        ["telemetry_id"],
        unique=False,
    )
    op.create_index(
        "ix_anomaly_rule_detected_at",
        "anomaly_records",
        ["rule_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_anomaly_severity_detected_at",
        "anomaly_records",
        ["severity", "detected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_anomaly_severity_detected_at", table_name="anomaly_records")
    op.drop_index("ix_anomaly_rule_detected_at", table_name="anomaly_records")
    op.drop_index(op.f("ix_anomaly_records_telemetry_id"), table_name="anomaly_records")
    op.drop_table("anomaly_records")
    # ### end Alembic commands ###
