"""create correlations

Revision ID: e819fb574bb1
Revises: 429cf66dee96
Create Date: 2026-09-16 11:23:22.126447

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e819fb574bb1"
down_revision: str | Sequence[str] | None = "429cf66dee96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correlations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("root_cause_anomaly_id", sa.Uuid(), nullable=False),
        sa.Column("root_cause_incident_id", sa.Uuid(), nullable=False),
        sa.Column("root_cause_confidence", sa.Float(), nullable=False),
        sa.Column("root_cause_reasons", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["root_cause_anomaly_id"], ["anomaly_records.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["root_cause_incident_id"], ["incidents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["monitored_services.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_correlation_created_at", "correlations", ["created_at"], unique=False
    )
    op.create_index(
        "ix_correlation_service_status",
        "correlations",
        ["service_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlations_root_cause_anomaly_id"),
        "correlations",
        ["root_cause_anomaly_id"],
        unique=False,
    )
    op.create_table(
        "correlation_incidents",
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["correlation_id"], ["correlations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("correlation_id", "incident_id"),
        sa.UniqueConstraint("incident_id", name="uq_correlation_incidents_incident_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("correlation_incidents")
    op.drop_index(
        op.f("ix_correlations_root_cause_anomaly_id"), table_name="correlations"
    )
    op.drop_index("ix_correlation_service_status", table_name="correlations")
    op.drop_index("ix_correlation_created_at", table_name="correlations")
    op.drop_table("correlations")
    # ### end Alembic commands ###
