"""create monitored services and telemetry records

Revision ID: fbdf46a4e529
Revises:
Create Date: 2026-09-15 09:55:32.568990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbdf46a4e529"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitored_services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "environment", name="uq_monitored_services_name_environment"
        ),
    )
    op.create_table(
        "telemetry_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("telemetry_type", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["monitored_services.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telemetry_records_observed_at"),
        "telemetry_records",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_records_source"),
        "telemetry_records",
        ["source"],
        unique=False,
    )
    op.create_index(
        "ix_telemetry_service_observed_at",
        "telemetry_records",
        ["service_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_telemetry_type_observed_at",
        "telemetry_records",
        ["telemetry_type", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_telemetry_type_observed_at", table_name="telemetry_records")
    op.drop_index("ix_telemetry_service_observed_at", table_name="telemetry_records")
    op.drop_index(op.f("ix_telemetry_records_source"), table_name="telemetry_records")
    op.drop_index(
        op.f("ix_telemetry_records_observed_at"), table_name="telemetry_records"
    )
    op.drop_table("telemetry_records")
    op.drop_table("monitored_services")
    # ### end Alembic commands ###
